### ISSUE TITLE
Generate bank holidays for 2018

### ISSUE THREAD

**Issue by fofr** [alphagov/calendars#131]
Users are searching for 2018 bank holiday dates but we haven't generated them yet.

See feedback here:
https://support.publishing.service.gov.uk/anonymous_feedback?path=/bank-holidays

![screen shot 2016-12-19 at 11 14 39](https://cloud.githubusercontent.com/assets/319055/21310911/6b40141a-c5dc-11e6-8fab-6f5b151f2d42.png)

Here's the PR for last year:
https://github.com/alphagov/calendars/pull/106

**Comment by davidbasalla** [comment]
See https://github.com/alphagov/calendars/pull/133
