### ISSUE TITLE
Calendar ICS file doesn't indicate when bank holidays are substitute days

### ISSUE THREAD

**Issue by fofr** [alphagov/calendars#132]
![screen shot 2016-12-19 at 11 26 31](https://cloud.githubusercontent.com/assets/319055/21311210/04f2da10-c5de-11e6-93d9-bf0d70e8bf09.png)

The ICS file should match the text on the bank holidays page:

![screen shot 2016-12-19 at 11 26 52](https://cloud.githubusercontent.com/assets/319055/21311225/168c6b2e-c5de-11e6-9b70-787b6a169ab4.png)

**Comment by nickcolley** [comment]
Also the main block misses this detail.

See also https://twitter.com/v21/status/813731849868603393

**Comment by boffbowsh** [comment]
Tracked on Trello

**Comment by fofr** [comment]
@boffbowsh What's the Trello link?

**Comment by boffbowsh** [comment]
Private atm, I need to get it added to the GOV.UK org and made public :(

**Comment by fofr** [comment]
As a GOVUK developer without access/links to that issue tracker, I'd be inclined to keep this open.

**Comment by boffbowsh** [comment]
https://trello.com/c/6QwB4LLg/478-calendar-ics-file-doesn-t-indicate-when-bank-holidays-are-substitute-days can't be public due to other cards on the board. Added you to the board.
