### ISSUE TITLE
Poor contrast on tab hover state

### ISSUE THREAD

**Issue by fofr** [alphagov/calendars#150]
https://www.gov.uk/bank-holidays#northern-ireland

When hovering on a tab the background colour is too dark to read the text.

The tab must clearly identify the hover state with sufficient contrast but also maintain readability of the tab.

![screen shot 2017-08-10 at 11 58 16](https://user-images.githubusercontent.com/319055/29167668-3fa0344e-7dc3-11e7-9743-dc388709fc94.png)

**Comment by tijmenb** [comment]
Now tracked here: https://trello.com/c/FMkKkRk8
