### ISSUE TITLE
Bunting is not defined

### ISSUE THREAD

**Issue by labooner** [alphagov/calendars#678]
Hi,

We're late to the party and just discovered these calendars. They're very much appreciated!

We're curious as to what a "buntable" holiday is (aka `"bunting": true`). We couldn't find any documentation on it. Current guess is that non-bunting holidays can't be bumped to the next working day?

Thanks

**Comment by issyl0** [comment]
Great to hear you like the calendars, @labooner! The bunting is a bit of fun! It appears on all bank holidays where the `bunting:` attribute is `true`. At Christmas, the flags turn into tinsel.

<img width="1046" alt="Screenshot 2019-12-03 at 11 39 33" src="https://user-images.githubusercontent.com/355033/70048217-ac313980-15c1-11ea-8055-128b6bd79d44.png">
