### ISSUE TITLE
Incorrect output with double bank holidays

### ISSUE THREAD

**Issue by dracos** [alphagov/calendars#73]
When New Year's Day is a Saturday (okay, so this doesn't happen again 2022 now, after 2011, but still), `lib/bank_holiday_generator.rb` will, if I've read it right, set New Year's Day and 2nd January both to Monday 3rd January. What should happen is the 2nd is moved to 3rd automatically by statute, and the 4th will usually be manually added by proclamation (so if this script is only outputting the statutory setup, it should technically leave it on the Saturday).

A similar issue with Christmas/Boxing Days 2021, where the code will currently set both Christmas Day and Boxing Day to 27th December, missing the 28th (again, added by proclamation as a replacement for Christmas Day).

Hope that's helpful.

**Comment by camilleldn** [comment]
Probably ok to close this own now, unless your concerns have not been addressed in #86 @dracos? :)

**Comment by dracos** [comment]
Great, thanks :) Wonder if the code will still be in use when it comes around ;)
