### ISSUE TITLE
Sequential event UIDs cause .ics events to be omitted and break format guidelines

### ISSUE THREAD

**Issue by odub** [alphagov/calendars#753]
Hi,

Thanks for all your work making this system.

### Problem

I experienced an issue in Google Calendar where ICS events between 2017 and early 2020 are being omitted. Here's what I see using Google Calendar to view all events:

![screencapture-calendar-google-calendar-embed-2019-12-26-16_28_36](https://user-images.githubusercontent.com/1530044/71483004-7e749480-27fd-11ea-84eb-06f7c0d36133.png)

### Replication steps

1) Visit https://calendar.google.com/calendar/r/settings/addbyurl
2) Enter https://www.gov.uk/bank-holidays/england-and-wales.ics into the URL field
3) Submit and observe missing events in the resulting calendar

Alternatively you can view the the problem via the premade example calendar [here](https://calendar.google.com/calendar/embed?src=ndic0dcrdsp2n3k15p1e5fv8s1ikvtf4%40import.calendar.google.com&ctz=Europe%2FLondon)

### Root cause

Surprisingly, when I investigated this the missing events were found correct and present in the latest data here:
https://www.gov.uk/bank-holidays/england-and-wales.ics

For example, 2020 New Year's Day (which is missing from gcal) shows up fine:
```ics
BEGIN:VEVENT
DTEND;VALUE=DATE:20200102
DTSTART;VALUE=DATE:20200101
SUMMARY:New Year’s Day
UID:ca6af7456b0088abad9a69f9f620f5ac-40@gov.uk
SEQUENCE:0
DTSTAMP:20191224T094854Z
END:VEVENT
```

However it's also notable that the first event shown in Google Calendar is New Year's Day 2012. In the .ics source it's New Year's Day 2015:
```ics
BEGIN:VEVENT
DTEND;VALUE=DATE:20150102
DTSTART;VALUE=DATE:20150101
SUMMARY:New Year’s Day
UID:ca6af7456b0088abad9a69f9f620f5ac-0@gov.uk
SEQUENCE:0
DTSTAMP:20191224T094854Z
END:VEVENT
```

Given the scenario, the bug I'm experiencing is likely a caching issue external to this service.

However, it's also really likely that the underlying issue is _this_ service's [use of sequential UIDs on ics `VEVENTS`](https://github.com/alphagov/calendars/blob/7d4bf00bba7e7ac6249903df5b99ff6dc1574664/lib/ics_renderer.rb#L25). I notice that [3 years of historical data were recently deleted](https://github.com/alphagov/calendars/commit/c28e7b570c39a10f60d2ed13b85d477b9a60159e#diff-1569053def8d48383b565a3d2d505529). Assuming that UIDs are used for cache lookups on events, this would create cache collisions for exactly the missing period described above.

[Here's](https://tools.ietf.org/html/rfc5545#section-3.8.4.7) the relevant section of the .ics spec stating that event UIDs should be globally unique. This calendar should definitely follow the format!

### Potential solutions

I see several routes to fixing the described issue.

Any of these would work:
1) Ask the Google Calendar team to manually invalidate their cache for all the GOV.UK bank holiday ics URLs
2) Revert [this commit](https://github.com/alphagov/calendars/commit/c28e7b570c39a10f60d2ed13b85d477b9a60159e#diff-1569053def8d48383b565a3d2d505529)
3) Reimplement [this function](https://github.com/alphagov/calendars/blob/7d4bf00bba7e7ac6249903df5b99ff6dc1574664/lib/ics_renderer.rb#L31-L34) to return globally unique ids as per the .ics standard (any GDS caching layers in front of this service would also need to be invalidated)

1 or 2 would only work if no bank holidays were ever deleted in future.

I'm happy to make a PR for the third implementation route if you need a hand. It seems like the best way forward to me.

Cheers! Happy new year!

**Comment by cbaines** [comment]
Hi @odub ,

Thanks for noticing this, I'll take a look at finding some time to fix this.

**Comment by odub** [comment]
Thanks for looking, good to hear

**Comment by odub** [comment]
Wow, this seems like great work! Thank you all. I'm looking forward to seeing the result go into production
